#3 Creating contribution guide
SuperLesson/SuperLesson pull request #26
Opened 2023-09-13 14:09 UTC by alvesisaque

Closes: https://github.com/SuperLesson/SuperLesson/issues/3

2023-09-14 22:46 UTC, isinyaaa requested changes
We should probably add sections on code style (following the PEP-8) and point to the readme for instructions on development. Please format this to use 80-chars per line as we're already doing on other documents as well. We can add a section about documenting the project once we decide on a guideline or at least a method (is it gonna be the wiki)?

2023-09-14 22:46 UTC, isinyaaa commented on CONTRIBUTING.md
> +Be sure to include a *title and clear description*, as much relevant information as possible, and a *code sample* or an *executable test case* demonstrating the expected behavior that is not occurrin
```suggestion
Be sure to include a *concise title* and a *clear description*, and be as thorough as possible. Also, include a *test case* demonstrating the unexpected behavior.
```

I don't think it makes sense to mention code samples, as we're not providing a library.

2023-09-14 22:46 UTC, isinyaaa commented on CONTRIBUTING.md
> +### Did you find a bug?
Please use only `##` in section headers.

Edit: actually, apart from the first header (title, just above), remove a `#` from all the others.

2023-09-14 22:46 UTC, isinyaaa commented on CONTRIBUTING.md
> +Feature development branches will be created from the *main* branch using the standard nomenclature `x_issue_name`, where `x` represents the issue tracking code.
TBH I feel this whole section is unnecessary. External contributors (i.e. the ones addressed in this file) couldn't care less about such details. Let's keep this private.

2023-09-14 22:46 UTC, isinyaaa commented on CONTRIBUTING.md
> +```
As discussed, we could actually refer to standard OSS contributing guides, that specify:
- Commit messages use imperative voice
- Descriptions detail WHAT and WHY, but never HOW (that's on code!)
- Reference issues and commits respectively with
  ```
  Closes: #123
  Fixes: abc0304 ("Commit message here")
  ```
  as necessary.
- It's a good idea to use git's standards for message length, such as 50 characters on the message and 72 on the description. Many IDEs and editors may already do that but it's good to specify.
- I like the part on `Co-authored-by: ...`, please keep it, but could be shorter too. Also, change `both` to something more general.

As for the example, let's get the issue number out of there, something like

```raw
CONTRIBUTING: Fix authorship info

Authorship info should also include co-authors, as those have also helped code
a certain contribution. As git doesn't account for possible co-authorship,
let's use commit tags.
```

Now, something a little more opinionated: I really like using commit prefixes to help figure out what a specific change dealt with before I even look at `--name-stat` or the rest of the message. But again, using `--name-stat` pretty much solves this issue... But it would be just like the example I gave (instead of e.g. "Fix authorship info in contribution guide" (so you see this information would probably always be present one way or another...).

2023-09-14 22:46 UTC, isinyaaa commented on CONTRIBUTING.md
> +Pull requests should be made to the main branch. The pull request's content must include a clear description of what was done.
```suggestion
Pull requests should be made to the main branch. The pull request's description must include a clear description of what was done.
```

2023-09-14 22:46 UTC, isinyaaa commented on CONTRIBUTING.md
> +If there is a need to update the *main* branch before completing the issue, the pull request name must contain `WIP:<X_branch_name>` so that the branch is not deleted.
Actually, I don't think I get this one, could you clarify?

2023-09-14 22:46 UTC, isinyaaa commented on CONTRIBUTING.md
> +One or more team members who did not participate in the modifications must conduct the code review. After the code review approval by the team members, it is possible to accept the PullRequest.
Again, specific info to use, you could just say that "there must be always two reviewers" but again, github UI shows this info now.

2023-09-14 22:46 UTC, isinyaaa commented on CONTRIBUTING.md
> +If you have any question, please send an email to isaque.alves@usp.br
I wouldn't list my email in here, maybe create another discussion at https://github.com/SuperLesson/SuperLesson/discussions

2023-09-14 22:46 UTC, isinyaaa commented on CONTRIBUTING.md
> +To create an issue, the [Issue Template](https://github.com/SuperLesson/SuperLesson/.github/ISSUE_TEMPLATE/feature_request.md) must be followed.
Most of this info is not necessary in here. Also, most people will voluntarily follow the template...

2023-09-18 18:04 UTC, alvesisaque commented on CONTRIBUTING.md
> +Feature development branches will be created from the *main* branch using the standard nomenclature `x_issue_name`, where `x` represents the issue tracking code.
I understand that since our last meeting, it has been decided that this plan will not be put into action. I will remove it.

2023-09-19 18:46 UTC, isinyaaa commented on CONTRIBUTING.md
> +* Create a [*feature request*](CONTRIBUTING.md#issue-policy)
This should come first. The user should only fork if they already have something to work on.

I'd separate the instructions for contributions to make this especially clear.

2023-09-19 18:46 UTC, isinyaaa commented on CONTRIBUTING.md
> +Veja a política de merges no tópico .
Oops, this line again. Please remove it.

2023-09-19 18:47 UTC, isinyaaa commented on CONTRIBUTING.md
> +
Nit: double empty lines.

2023-09-19 18:48 UTC, isinyaaa commented on CONTRIBUTING.md
> +Co-authored-by: Autor 2 <autor2@gmail.com>
nit: I wouldn't use a real domain for these example emails.

2023-09-19 18:48 UTC, isinyaaa commented on CONTRIBUTING.md
> +Please follow to the [Pull Request Template](https://github.com/SuperLesson/SuperLesson/.github/pull_request_template.md).
```suggestion
Please follow the [Pull Request Template](https://github.com/SuperLesson/SuperLesson/.github/pull_request_template.md).
```

2023-09-19 18:49 UTC, isinyaaa commented on CONTRIBUTING.md
> +
Nit: ditto.

2023-09-19 18:49 UTC, isinyaaa commented on CONTRIBUTING.md
> +    ```
```suggestion
    ```raw
```

2023-09-19 18:50 UTC, isinyaaa commented on CONTRIBUTING.md
> +```
nit: ditto.

```suggestion
```raw
```

2023-09-19 18:51 UTC, isinyaaa requested changes
Some comments and nitpicks inline. This is already looking better. But we still need to add a reference (at least) to PEP-8.

2023-09-23 17:55 UTC, isinyaaa approved these changes
lgtm

2023-09-23 17:55 UTC, merged