Docker
SuperLesson/SuperLesson pull request #37
Opened 2023-09-19 16:18 UTC by rsgrava

## Description
Closes #23.
This introduces a dockerfile which containerizes the application into a CUDA 11 ready environment, with all necessary dependencies.
It also documents the steps necessary to build and run this container.

## Pull Request Requirements
- [X] I have linked my pull request to the corresponding issue (if it exists).
- [X] I have updated the documentation (if necessary).
- [ ] I have added tests that prove my fix is effective or that my feature works (if necessary).

2023-09-19 18:30 UTC, isinyaaa commented on Dockerfile
> +ENV NAME SuperLesson
what is this for?

2023-09-19 18:33 UTC, isinyaaa commented on Dockerfile
> +ENV NAME SuperLesson
Please add a `CMD` at the end to execute transcription when we run the container.

2023-09-19 18:34 UTC, isinyaaa commented on Dockerfile
> +COPY . /SuperLesson
We probably don't want to be copying that all the time, especially taking into consideration that the lessons folder could be full of other stuff. It's probably a better idea to make a shared volume.

2023-09-19 18:37 UTC, isinyaaa requested changes
Please squash the two commits. Other comments inline.

2023-09-19 18:51 UTC, rsgrava commented on Dockerfile
> +    poetry install;
Noted. Will change

2023-09-19 18:52 UTC, rsgrava commented on Dockerfile
> +    poetry install;
Yes. `WORKDIR /SuperLesson` places us there.

2023-09-19 18:53 UTC, isinyaaa commented on Dockerfile
> +    poetry install;
oh you're right.

2023-09-19 18:56 UTC, rsgrava commented on Dockerfile
> +ENV NAME SuperLesson
Should this be done now? The command for running transcription might change as soon as we decide on the proper interface commands. As it currently stands on main, it will have to execute everything in one go.

2023-09-19 18:59 UTC, isinyaaa commented on Dockerfile
> +ENV NAME SuperLesson
I was also thinking about that just now. The container won't be so useful if we have to manually manage stuff running inside it (it's just a terrible interface) so it's probably better to provide the `poetry run transcription` or something before we merge this PR.

2023-09-19 19:01 UTC, isinyaaa commented on Dockerfile
> +ENV NAME SuperLesson
+ it would also be nice if we could separate dependencies by [groups in poetry](https://python-poetry.org/docs/managing-dependencies/#dependency-groups) so we can only install `transcription-related` stuff on this container. I'm not sure if there's a use case for running the entire thing on containers tho.

2023-09-19 19:04 UTC, rsgrava commented on Dockerfile
> +COPY . /SuperLesson
Good idea, noted.

2023-09-19 19:06 UTC, rsgrava commented on Dockerfile
> +ENV NAME SuperLesson
Merely for setting an environment variable with the container's name. Can be removed if it won't be used.

2023-09-19 19:14 UTC, isinyaaa commented on Dockerfile
> +ENV NAME SuperLesson
I'd rather it be removed if there's no use now. If we need it, we add it later.

2023-09-27 20:57 UTC, isinyaaa commented
I'm drafting this as we're not tackling it atm.

2023-10-11 14:39 UTC, evaporei commented on Dockerfile
> +    poetry install;
not exactly btw, it's good to separate them if you see reuse in other images and expect caching

https://stackoverflow.com/questions/39223249/multiple-run-vs-single-chained-run-in-dockerfile-which-is-better

2023-10-23 21:51 UTC, isinyaaa commented on Dockerfile
> +COPY README.md /SuperLesson
```suggestion
COPY poetry.lock .
COPY pyproject.toml .
COPY README.md .
```

2023-10-23 21:51 UTC, isinyaaa commented on Dockerfile
> +COPY superlesson/. /SuperLesson/superlesson
```suggestion
COPY superlesson .
```

2023-10-23 21:57 UTC, isinyaaa approved these changes

2023-10-23 21:57 UTC, merged